#!/bin/bash

echo "determining branch"

if ! [ -t 0 ]; then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ "master" == "$branch" ]; then
	../autobuild.sh	
fi



if [ "staging" == "$branch" ]; then
  echo 'staging was pushed'
fi


echo "done"
